=== JJMUNPER/LMSGI_UD4/Concesionario/concesionario.dtd
<!ELEMENT concesionario (coche*)>
<!ELEMENT coche (codigodecoche, marca, modelo, matricula, potencia, plazas, numerodepuertas)>
<!ELEMENT codigodecoche (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT potencia (#PCDATA)>
<!ELEMENT plazas (#PCDATA)>
<!ELEMENT numerodepuertas (#PCDATA)>

=== JJMUNPER/LMSGI_UD4/Concesionario/concesionario.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
    <!DOCTYPE concesionario SYSTEM "concesionario.dtd">
    <concesionario>
        <coche>
            <codigodecoche>01</codigodecoche>
            <marca>Renault</marca>
            <modelo>Laguna</modelo>
            <matricula>ca6269bt</matricula>
            <potencia>120</potencia>
            <plazas>5</plazas>
            <numerodepuertas>4</numerodepuertas>
        </coche>
        <coche>
            <codigodecoche>02</codigodecoche>
            <marca>Ford</marca>
            <modelo>Focus</modelo>
            <matricula>5564dft</matricula>
            <potencia>110</potencia>
            <plazas>5</plazas>
            <numerodepuertas>5</numerodepuertas>
        </coche>
        <coche>
            <codigodecoche>03</codigodecoche>
            <marca>Citroen</marca>
            <modelo>Picaso</modelo>
            <matricula>4782hhs</matricula>
            <potencia>90</potencia>
            <plazas>5</plazas>
            <numerodepuertas>5</numerodepuertas>

        </coche>
        <coche>
            <codigodecoche>04</codigodecoche>
            <marca>Toyota</marca>
            <modelo>Gt86</modelo>
            <matricula>4217gjk</matricula>
            <potencia>150</potencia>
            <plazas>2</plazas>
            <numerodepuertas>3</numerodepuertas>
        </coche>
        <coche>
            <codigodecoche>05</codigodecoche>
            <marca>Kia</marca>
            <modelo>Ceed</modelo>
            <matricula>5788ldd</matricula>
            <potencia>105</potencia>
            <plazas>5</plazas>
            <numerodepuertas>5</numerodepuertas>
        </coche>
    </concesionario>
